listen_addresses = '*'
port = 5433
max_connections = 100
password_encryption = 'scram-sha-256'
shared_buffers = '2GB'
effective_cache_size = '6GB'
maintenance_work_mem = '512MB'
work_mem = '8MB'
wal_buffers = '16MB'
min_wal_size = '1GB'
max_wal_size = '4GB'
checkpoint_completion_target = 0.9
wal_compression = on

hot_standby = on
restore_command = 'cp /var/lib/pgsql/shp/wal-archive/%f %p'
